# Modified for the Career Agent public edition (2026-09-22). See NOTICE.
"""Technology / skill lexicon, aliases and concept groups.

Deterministic term detection is the foundation of grounding: the same
normalized term appears in JD requirements, evidence records and generated
bullets, so "does this bullet mention a tool its evidence does not vouch for"
becomes a set-difference rather than a judgement call.

The lexicon is deliberately broad (it includes tools the candidate has never
used) because gap detection needs to *recognise* an unsupported technology in
a JD or in generated prose.
"""

from __future__ import annotations

import re
from functools import lru_cache

# canonical term -> aliases (all lowercase). Canonical forms are lowercase too.
ALIASES: dict[str, list[str]] = {
    "power bi": ["powerbi", "power-bi", "microsoft power bi"],
    "power query": ["powerquery", "m language"],
    "dax": [],
    "power automate": ["microsoft flow", "ms flow"],
    "power apps": ["powerapps"],
    "sql": ["t-sql", "pl/sql", "structured query language"],
    "python": ["python3"],
    "javascript": ["js", "ecmascript", "vanilla javascript", "vanilla js"],
    "typescript": ["ts"],
    "node.js": ["node", "nodejs", "node js"],
    "react": ["reactjs", "react.js"],
    "vue": ["vuejs", "vue.js"],
    "angular": ["angularjs"],
    "html": ["html5"],
    "css": ["css3"],
    "tailwind css": ["tailwind", "tailwindcss"],
    "java": [],
    "c#": ["csharp", ".net", "dotnet"],
    "golang": ["go lang", "go language"],  # never bare "go"
    "ruby": ["ruby on rails", "rails"],
    "php": [],
    "r": [],
    "scala": [],
    "bash": ["shell scripting", "shell"],
    "powershell": [],
    "linux": [],
    "rest apis": [
        "rest",
        "rest api",
        "restful",
        "restful apis",
        "restful api",
        "http apis",
        "api",
        "apis",
        "web apis",
    ],
    "graphql": ["graphql apis", "graphql api"],
    "soap": ["soap apis"],
    "webhooks": ["webhook"],
    "oauth": ["oauth2", "oauth 2.0"],
    "json": [],
    "xml": [],
    "csv": [],
    "postman": [],
    "openapi": ["swagger"],
    "git": ["github", "gitlab", "bitbucket", "version control"],
    "ci/cd": [
        "cicd",
        "ci cd",
        "continuous integration",
        "continuous deployment",
        "continuous delivery",
        "github actions",
        "jenkins",
    ],
    "docker": ["containers"],
    "kubernetes": ["k8s"],
    "terraform": [],
    "aws": ["amazon web services", "lambda", "aws lambda", "s3"],
    "azure": ["microsoft azure"],
    "gcp": ["google cloud", "google cloud platform"],
    "netlify": [],
    "vercel": [],
    "serverless": ["serverless functions", "cloud functions"],
    "workato": [],
    "zapier": [],
    "n8n": [],
    "make.com": ["make (formerly integromat)", "integromat", "make automation"],
    "boomi": ["dell boomi"],
    "mulesoft": ["mule", "anypoint"],
    "celigo": [],
    "tray.io": ["tray"],
    "ipaas": ["integration platform", "integration platform as a service"],
    "workday": ["workday hcm", "workday integration", "workday studio"],
    "sap": ["sap erp", "sap s/4hana", "s/4hana", "sap ecc"],
    "netsuite": ["oracle netsuite", "suitescript"],
    "oracle database": ["oracle db", "oracle sql", "oracle"],
    "oracle erp": ["oracle fusion", "oracle cloud erp", "oracle ebs"],
    "dynamics 365": ["microsoft dynamics", "dynamics crm", "dynamics"],
    "quickbooks": ["quickbooks online", "qbo"],
    "xero": [],
    "sage": ["sage intacct", "intacct"],
    "stripe": ["stripe billing", "stripe subscriptions"],
    "chargebee": [],
    "zuora": [],
    "recurly": [],
    "braintree": [],
    "adyen": [],
    "hubspot": [
        "hubspot crm",
        "hubspot cms",
        "hubspot marketing hub",
        "hubspot sales hub",
        "hubspot operations hub",
    ],
    "salesforce": ["sfdc", "salesforce crm", "sales cloud", "service cloud", "salesforce.com"],
    "salesforce administration": ["salesforce admin", "salesforce administrator", "sfdc admin"],
    "apex": ["salesforce apex"],
    "soql": [],
    "salesforce flow": ["flow builder", "salesforce flows"],
    "salesforce cpq": ["cpq"],
    "marketing cloud": ["salesforce marketing cloud", "sfmc"],
    "pardot": ["account engagement"],
    "marketo": [],
    "cdp": ["customer data platform", "customer data platforms", "customer-data platform"],
    "treasure data": ["treasure ai", "treasure data cdp"],
    "adobe analytics": [],
    "cja": ["customer journey analytics", "adobe cja", "adobe customer journey analytics"],
    "marketing automation": [
        "marketing automation platform",
        "marketing automation platforms",
        "marketing automations",
    ],
    "segmentation": ["audience segmentation", "customer segmentation", "audience segments"],
    "analytics": ["web analytics", "digital analytics", "analytics platforms"],
    "data flows": ["data flow", "integration flows", "data synchronization flows"],
    "data discrepancies": ["data discrepancy", "discrepancies", "tracking discrepancies"],
    "platform governance": ["well-governed", "well governed", "platform governance"],
    "eloqua": [],
    "braze": [],
    "iterable": [],
    "klaviyo": [],
    "mailchimp": [],
    "customer.io": [],
    "segment": ["twilio segment"],
    "mparticle": [],
    "google analytics": ["ga4", "universal analytics"],
    "google tag manager": ["tag manager"],  # never bare "gtm": it means go-to-market in most JDs
    "mixpanel": [],
    "amplitude": [],
    "looker": ["looker studio", "google data studio", "data studio"],
    "tableau": [],
    "qlik": ["qlikview", "qlik sense"],
    "mode": ["mode analytics"],
    "sisense": [],
    "snowflake": [],
    "bigquery": ["big query"],
    "redshift": ["amazon redshift"],
    "databricks": [],
    "dbt": [],
    "airflow": ["apache airflow"],
    "fivetran": [],
    "spark": ["pyspark", "apache spark"],
    "kafka": ["apache kafka"],
    "postgresql": ["postgres", "psql"],
    "mysql": [],
    "sql server": ["mssql", "microsoft sql server"],
    "mongodb": ["mongo"],
    "redis": [],
    "firebase": [],
    "supabase": ["superbase"],
    "airtable": [],
    "google sheets": ["gsheets", "sheets"],
    "excel": ["vlookup", "pivot tables"],
    "smartsheet": [],
    "notion": [],
    "asana": [],
    "monday.com": ["monday"],
    "clickup": [],
    "jira": ["atlassian jira"],
    "confluence": [],
    "zendesk": [],
    "servicenow": [],
    "intercom": [],
    "freshdesk": [],
    "slack": [],
    "microsoft teams": ["ms teams", "msft teams"],
    "outlook": ["outlook calendar", "microsoft outlook"],
    "google workspace": ["g suite", "gsuite"],
    "sharepoint": [],
    "deel": ["deel api"],
    "rippling": [],
    "gusto": [],
    "bamboohr": ["bamboo hr"],
    "adp": ["adp workforce now"],
    "paylocity": [],
    "ukg": ["ultipro", "kronos"],
    "successfactors": ["sap successfactors"],
    "fountain": ["fountain ats"],
    "greenhouse": [],
    "lever": [],
    "ashby": [],
    "icims": [],
    "docusign": [],
    "pandadoc": [],
    "jotform": [],
    "typeform": [],
    "twilio": [],
    "sendgrid": [],
    "shopify": [],
    "magento": ["adobe commerce"],
    "pipefy": [],
    "okta": [],
    "active directory": ["azure ad", "entra id"],
    "figma": [],
    "llm": [
        "llms",
        "large language models",
        "large language model",
        "generative ai",
        "genai",
        "gen ai",
    ],
    "rag": ["retrieval-augmented generation", "retrieval augmented generation"],
    "ai agents": ["agentic", "agents", "ai agent", "agent orchestration", "multi-agent"],
    "openai": ["gpt", "chatgpt", "openai api"],
    "anthropic": ["claude", "claude api"],
    "claude code": [],
    "codex": [],
    "langchain": [],
    "langgraph": ["lang graph"],
    "llamaindex": ["llama index", "llama-index"],
    # API frameworks are named products: REST-API experience never proves one of them
    "fastapi": ["fast api"],
    "flask": [],
    "django": [],
    "vector database": ["vector db", "pinecone", "weaviate", "chroma", "pgvector"],
    "ollama": [],
    "prompt engineering": ["prompting", "prompt design"],
    "mcp": ["mcp servers", "mcp server", "model context protocol"],
    "function calling": ["tool calling", "tool/function calling", "agent tools"],
    "guardrails": ["guardrail"],
    "llm evaluation": ["evals", "evaluations", "agent evaluation"],
    "metabase": [],
    "advanced excel": ["excel skills", "microsoft excel"],
    "month-end close": ["month end close", "monthly close", "close process", "month-end"],
    "financial analysis": ["fp&a", "financial planning"],
    "root cause analysis": ["root cause", "rca"],
    "employee relations": ["employee relations platforms", "er cases", "workplace investigations"],
    "case management": ["case-management"],
    "saas implementation": [
        "customer implementation",
        "onboarding of customers",
        "implementation projects",
        "implementation consulting",
        "post-sales implementation",
        "solution implementation",
    ],  # never bare "implementation"
    "technical account management": ["technical account manager", "tam"],
    "log analysis": ["logs"],
    "security best practices": ["security"],
    "hubspot workflows": ["lifecycle stages", "hubspot objects", "hubspot properties"],
    "machine learning": ["ml"],
    "ai": [
        "artificial intelligence",
        "ai tools",
        "ai-powered",
        "ai powered",
        "ai-first",
        "ai workflows",
        "ai-assisted",
    ],
    "accounting": ["accountants"],
    "general ledger": ["gl", "gl accounts", "ledger"],
    "chart of accounts": ["coa"],
    "no-code automation": [
        "no-code",
        "no code",
        "low-code",
        "no-code automation tools",
        "no-code tools",
        "no-code builder",
    ],
    "project delivery": [
        "project planning",
        "project plans",
        "delivery management",
        "implementation management",
        "project timelines",
        "timelines",
        "release management",
        "phased rollout",
        "program delivery",
        "planning through launch",
        "kickoff through launch",
        "through successful launch",
        "end-to-end delivery",
        "delivered end to end",
        "delivered end-to-end",
    ],
    "client enablement": [
        "customer enablement",
        "customer onboarding",
        "client onboarding",
        "platform setup",
        "guide clients",
        "onboarding optimization",
        "onboarding experience",
        "enterprise implementation projects",
        "enablement",
    ],
    "risk management": [
        "risk assessment",
        "risk register",
        "risks and blockers",
        "blast radius",
        "risk analysis",
        "identify risks",
    ],
    "incident management": [
        "escalation",
        "escalations",
        "incident triage",
        "incident response",
        "coordinate escalation",
    ],
    "dependency mapping": [
        "downstream dependencies",
        "dependency analysis",
        "downstream impact",
        "map downstream",
    ],
    "system of record": ["source of truth", "systems of record"],
    "funnel building": ["funnels", "funnel", "landing page", "landing pages", "outbound funnels"],
    "margin analysis": ["margin", "margins", "gross margin"],
    "pricing analysis": ["price analysis", "pricing strategy", "pricing models"],
    "cash flow": [
        "cash movements",
        "cash flow analysis",
        "cash forecasting",
        "cash position",
        "cash management",
    ],
    "inventory": ["inventory management", "inventory analysis"],
    "cost analysis": ["cost movements", "cost accounting", "cost analysis"],
    "monthly business review": ["mbr", "business review"],
    "english": [
        "english proficiency",
        "english communication",
        "business-level english",
        "fluent english",
        "advanced english",
        "proficient english",
    ],
    "hr technology": ["hr tech", "people technology", "hr software"],
    "automation": [
        "automations",
        "process automation",
        "workflow automation",
        "business automation",
        "automation workflows",
    ],
    "systems integration": [
        "system integrations",
        "system integration",
        "integrations",
        "integration",
    ],
    "internal tools": ["internal tool", "internal tooling"],
    "etl": ["elt", "etl/elt", "data pipelines", "data pipeline"],
    "data modeling": ["data modelling", "data model"],
    "dimensional modeling": ["dimensional modelling", "star schema"],
    "dashboards": [
        "dashboard",
        "dashboard development",
        "reporting systems",
        "reporting workflows",
        "data reporting",
        "reporting system",
        "internal reporting",
    ],
    "reporting logic": [],
    "troubleshooting": [
        "troubleshoot",
        "production troubleshooting",
        "debugging",
        "diagnose",
        "diagnosing",
    ],
    "data warehouse": ["data warehousing", "dwh"],
    "data governance": [],
    "data quality": [
        "data validation",
        "data integrity",
        "data accuracy",
        "data cleaning",
        "clean data",
        "accurate data",
        "data accuracy and cleaning",
        "data is clean",
        "clean, accurate",
    ],
    "data reconciliation": ["reconciliation"],
    "revenue assurance": [],
    "subscription billing": ["recurring billing", "billing automation"],
    "quote-to-cash": ["quote to cash", "q2c"],
    "order-to-cash": ["order to cash", "o2c"],
    "lead routing": ["lead assignment", "round robin"],
    "lead scoring": [],
    "crm": ["crm systems", "crm platform", "crm administration"],
    "erp": ["erp systems"],
    "hris": ["hcm", "hr systems", "people systems"],
    "ats": ["applicant tracking system", "applicant tracking"],
    "bi": ["business intelligence"],
    "process mapping": [
        "as-is / to-be",
        "as-is/to-be",
        "as-is",
        "to-be",
        "process design",
        "process improvement",
        "bpmn",
        "workflow mapping",
        "diagramming",
        "diagram builds",
        "process diagrams",
        "flowcharts",
        "workflow inefficiencies",
        "process bottlenecks",
    ],
    "requirements gathering": ["requirements elicitation", "requirements", "discovery"],
    "solution architecture": [
        "solution design",
        "solutions architecture",
        "technical architecture",
    ],
    "technical documentation": ["documentation"],
    "uat": ["user acceptance testing", "acceptance testing"],
    "raci": [],
    "six sigma": ["lean six sigma", "green belt", "cssgb"],
    "certification": ["certified", "certifications", "certificate"],
    "agile": ["scrum", "kanban", "sprint"],
    "sox": ["sarbanes-oxley", "sox compliance"],
    "gaap": ["us gaap"],
    "asc 606": ["revenue recognition"],
    "accounts payable": ["ap"],
    "accounts receivable": ["ar"],
    "financial operations": ["finops", "finance operations"],
    "revenue operations": ["revops", "rev ops"],
    "sales operations": ["sales ops"],
    "marketing operations": [
        "marketing ops",
        "mops",
        "martech",
        "marketing technology",
        "marketing technology ecosystem",
    ],
    "customer success": ["cs"],
    # customer-operations practices: capabilities, never platforms; none of them is transferable from another
    "customer success operations": ["cs operations", "cs ops", "customer operations"],
    "customer health scoring": [
        "health scoring",
        "customer health score",
        "customer health scores",
        "health score",
    ],
    "customer lifecycle management": ["lifecycle management", "customer lifecycle"],
    "renewal operations": [
        "renewal and contract operations",
        "contract operations",
        "renewal ops",
        "renewals operations",
    ],
    "net revenue retention": ["nrr", "ndr", "net dollar retention"],
    "gross revenue retention": ["grr"],
    "logo retention": [],
    "people management": [
        "people manager",
        "direct reports",
        "manage a team",
        "managing a team",
        "team lead",
        "team leadership",
    ],
    "stakeholder management": [
        "stakeholders",
        "stakeholder",
        "stakeholder engagement",
        "cross-functional collaboration",
        "cross-functional",
        "non-technical stakeholders",
        "business partners",
    ],
    "communication": [
        "communication skills",
        "written and verbal",
        "verbal and written",
        "presentation skills",
    ],
    "bachelor's degree": [
        "bachelor",
        "bachelors",
        "bachelor's",
        "ba/bs",
        "bs/ba",
        "undergraduate degree",
        "degree",
    ],
    "business administration": ["bba"],
    "project management": ["project manager", "pmp", "program management"],
    "training": ["user training", "training material", "training materials"],
    "change management": ["change adoption", "rollout", "adoption"],
    "pre-sales": [
        "presales",
        "pre sales",
        "sales engineering",
        "solutions engineering",
        "solution engineering",
    ],
    "proof of concept": ["poc", "pocs", "proofs of concept"],
    "idempotency": ["idempotent"],
    "dead-letter queue": ["dead letter queue", "dlq"],
    "production monitoring": [
        "monitoring",
        "observability",
        "alerting",
        "alerts",
        "set up alerting",
    ],
    "error handling": ["failure handling", "fallbacks", "retries", "safe retries"],
    "unit testing": ["automated tests", "test automation", "pytest", "jest"],
    "tax": ["tax compliance"],
    "bookkeeping": [],
    "payroll": [],
    "compliance": ["regulatory compliance"],
    "finance": ["financial systems", "finance systems"],
    "recruiting": ["talent acquisition", "recruitment"],
    "insurance": ["insurance company", "insurer", "brokerage"],
    "compensation": ["comp plans", "commissions", "incentive compensation"],
    "outreach.io": ["outreach io"],  # never bare "outreach"
    "salesloft": [],
    "gong": [],
    "zoominfo": [],
    "clay": [],
    "leandata": [],
    "clearbit": [],
    "6sense": [],
    "demandbase": [],
    "apollo": ["apollo.io"],
    "linkedin sales navigator": ["sales navigator"],
    "wordpress": [],
    "webflow": [],
    "hubl": [],
    "cms": ["content management system"],
}

# Concept groups for transferable matching: a requirement for X where the
# candidate has evidence for Y in the same group is "transferable", not direct.
CONCEPT_GROUPS: dict[str, list[str]] = {
    "crm": ["hubspot", "salesforce", "dynamics 365", "pipedrive", "zoho crm", "crm"],
    "ipaas": [
        "workato",
        "zapier",
        "n8n",
        "make.com",
        "boomi",
        "mulesoft",
        "celigo",
        "tray.io",
        "power automate",
        "ipaas",
        "no-code automation",
    ],
    "bi": [
        "power bi",
        "tableau",
        "looker",
        "qlik",
        "metabase",
        "mode",
        "sisense",
        "bi",
        "dashboards",
    ],
    # deliberately no CRM-configuration group: Salesforce Flows/admin/CPQ must never be transferable from HubSpot work
    "erp": ["sap", "netsuite", "oracle erp", "dynamics 365", "quickbooks", "xero", "sage", "erp"],
    "hris": [
        "workday",
        "deel",
        "rippling",
        "gusto",
        "bamboohr",
        "adp",
        "paylocity",
        "ukg",
        "successfactors",
        "hris",
        "hr technology",
    ],
    "ats": ["fountain", "greenhouse", "lever", "ashby", "icims", "ats"],
    "billing": [
        "stripe",
        "chargebee",
        "zuora",
        "recurly",
        "braintree",
        "adyen",
        "subscription billing",
        "quote-to-cash",
        "order-to-cash",
    ],
    "database": [
        "sql",
        "postgresql",
        "mysql",
        "sql server",
        "oracle database",
        "supabase",
        "snowflake",
        "bigquery",
        "redshift",
        "mongodb",
    ],
    "warehouse": ["snowflake", "bigquery", "redshift", "databricks", "data warehouse"],
    "transform": ["dbt", "airflow", "fivetran", "etl", "power query", "spark"],
    "languages": ["python", "javascript", "typescript", "node.js"],
    "cloud": ["aws", "azure", "gcp", "serverless"],
    "hosting": ["netlify", "vercel"],
    "api": ["rest apis", "graphql", "soap", "webhooks", "oauth"],
    "ai": [
        "ai",
        "llm",
        "rag",
        "ai agents",
        "openai",
        "anthropic",
        "claude code",
        "codex",
        "langchain",
        "langgraph",
        "llamaindex",
        "ollama",
        "vector database",
    ],
    "api_frameworks": ["fastapi", "flask", "django"],
    "agent_frameworks": ["langchain", "langgraph", "llamaindex"],
    # only the reliability/quality pair is mutually transferable; prompt engineering, MCP and
    # function calling are deliberately ungrouped so they stay gaps unless literally evidenced
    "agent_quality": ["guardrails", "llm evaluation"],
    # NOTE: "employee relations" and "case management" are deliberately NOT in any group:
    # they must never become transferable from recruiting/payroll/compensation evidence.
    "hr_domain": ["recruiting", "payroll", "compensation"],
    # business-metric analysis is its own family: none of it is transferable from data-quality or reconciliation work
    "finance_analysis": [
        "financial analysis",
        "margin analysis",
        "pricing analysis",
        "cash flow",
        "inventory",
        "cost analysis",
        "monthly business review",
    ],
    "close_ops": [
        "month-end close",
        "data reconciliation",
        "revenue assurance",
        "accounts payable",
        "accounts receivable",
    ],
    "spreadsheet_skills": ["advanced excel", "excel", "google sheets", "airtable"],
    "implementation": [
        "saas implementation",
        "technical account management",
        "pre-sales",
        "proof of concept",
        "training",
        "change management",
        "client enablement",
    ],
    "delivery": ["project management", "project delivery"],
    "reliability_ops": [
        "production monitoring",
        "incident management",
        "risk management",
        "dependency mapping",
        "error handling",
        "troubleshooting",
    ],
    "ticketing": [
        "jira",
        "zendesk",
        "servicenow",
        "asana",
        "monday.com",
        "clickup",
        "intercom",
        "freshdesk",
    ],
    "marketing_automation": [
        "marketo",
        "pardot",
        "marketing cloud",
        "braze",
        "iterable",
        "klaviyo",
        "mailchimp",
        "customer.io",
    ],  # tools only; the marketing-ops domain is not a tool
    "product_analytics": [
        "google analytics",
        "mixpanel",
        "amplitude",
        "google tag manager",
        "adobe analytics",
        "cja",
    ],
    "cdp": ["cdp", "treasure data", "segment", "mparticle", "tealium", "rudderstack"],
    "governance": ["data governance", "platform governance"],
    "ecommerce": ["shopify", "magento"],
    "spreadsheets": ["excel", "google sheets", "airtable", "smartsheet"],
    "esign_forms": ["docusign", "pandadoc", "jotform", "typeform"],
    "devops": ["git", "ci/cd", "docker", "kubernetes", "terraform"],
    "collab": [
        "slack",
        "microsoft teams",
        "outlook",
        "google workspace",
        "sharepoint",
        "notion",
        "confluence",
    ],
    "process": [
        "process mapping",
        "requirements gathering",
        "solution architecture",
        "technical documentation",
        "uat",
        "raci",
        "six sigma",
        "agile",
        "change management",
        "training",
    ],
    "automation_general": [
        "automation",
        "systems integration",
        "internal tools",
        "ipaas",
        "marketing automation",
        "data flows",
    ],
    "soft": ["stakeholder management", "communication"],
    "finance_domain": [
        "finance",
        "financial operations",
        "accounts payable",
        "accounts receivable",
        "tax",
        "bookkeeping",
        "accounting",
        "payroll",
        "compliance",
        "revenue assurance",
        "sox",
        "gaap",
        "asc 606",
        "compensation",
    ],
    "gtm_domain": [
        "revenue operations",
        "sales operations",
        "marketing operations",
        "customer success",
        "lead routing",
        "lead scoring",
    ],
    "sales_eng": ["pre-sales", "proof of concept"],
    "quality": [
        "idempotency",
        "dead-letter queue",
        "unit testing",
        "data quality",
        "data reconciliation",
        "data governance",
        "data discrepancies",
    ],
    "error_handling_fam": ["error handling", "dead-letter queue", "idempotency"],
    "data_modeling": ["data modeling", "dimensional modeling", "data warehouse"],
}

# Requirement wording that implies administering/owning a platform rather than
# integrating with it. Integration-only evidence is capped at PARTIAL for these.
ADMIN_CUES = [
    "administrator",
    "administration",
    "admin",
    "configure",
    "configuration",
    "customize",
    "customization",
    "manage the platform",
    "platform owner",
    "system owner",
    "own the",
    "instance",
    "permissions",
    "user management",
    "roles and profiles",
    "validation rules",
    "workflow rules",
    "page layouts",
]

# Prose cues the validator uses to catch upgrades the evidence does not support.
EXPERTISE_CUES = [
    "expert",
    "expertise",
    "advanced knowledge",
    "deep expertise",
    "mastery",
    "guru",
    "specialist in",
]
ADMIN_PROSE_CUES = [
    "administered",
    "administrator",
    "administration of",
    "configured and administered",
    "owned the administration",
    "platform administration",
]
MANAGEMENT_PROSE_CUES = [
    "managed a team",
    "led a team of",
    "direct reports",
    "people manager",
    "managed engineers",
    "hired and managed",
    "managed a staff",
]

# Scope words that widen a claim without adding a tool or a number. Each must appear
# literally in the bound evidence record's own text, otherwise the clause is rejected.
SCOPE_CUES = [
    "company-wide",
    "companywide",
    "enterprise-wide",
    "organization-wide",
    "organisation-wide",
    "firm-wide",
    "across the company",
    "across the organization",
    "across the organisation",
    "across the business",
    "across all",
    "entire company",
    "entire organization",
    "entire organisation",
    "whole company",
    "all of finance",
    "all departments",
    "sole",
    "solely",
    "entire",
    "all",
    "every",
    "global",
    "worldwide",
    "international",
    "multi-country",
    "infrastructure",
    "at scale",
    "multi-million",
    "million-dollar",
    "revenue growth",
    "grew revenue",
    "increased revenue",
    "drove revenue",
    "generated revenue",
    "boosted revenue",
    "transformation",
    "transformed",
    "pioneered",
    "single-handedly",
    "from the ground up",
    "end-to-end ownership",
    "full ownership",
    "sole owner",
    "head of",
    "director",
    "executive",
    "c-suite",
    "c-level",
    "board",
    "strategy for the company",
    "company strategy",
    "mission-critical",
    "business-critical",
    "thousands",
    "hundreds",
    "dozens",
    "millions",
    "enterprise-scale",
    "large-scale",
    "fortune 500",
    "best-in-class",
    "world-class",
    "industry-leading",
]

# Verbs that assert ownership or leadership. Allowed only when the bound record has LED
# proficiency or uses the verb itself.
OWNERSHIP_VERBS = [
    "owned",
    "own",
    "led",
    "lead",
    "spearheaded",
    "headed",
    "directed",
    "founded",
    "championed",
    "oversaw",
    "orchestrated",
    "drove",
    "pioneered",
    "managed",
]

STOPWORDS = {
    "a",
    "an",
    "the",
    "and",
    "or",
    "of",
    "to",
    "in",
    "on",
    "for",
    "with",
    "by",
    "from",
    "as",
    "at",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "this",
    "that",
    "these",
    "those",
    "it",
    "its",
    "into",
    "over",
    "under",
    "across",
    "through",
    "via",
    "using",
    "use",
    "used",
    "will",
    "would",
    "can",
    "could",
    "should",
    "may",
    "might",
    "must",
    "we",
    "our",
    "you",
    "your",
    "they",
    "their",
    "he",
    "she",
    "her",
    "his",
    "i",
    "my",
    "me",
    "who",
    "whom",
    "which",
    "what",
    "when",
    "where",
    "how",
    "why",
    "not",
    "no",
    "yes",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "done",
    "than",
    "then",
    "also",
    "both",
    "each",
    "other",
    "such",
    "only",
    "own",
    "same",
    "so",
    "very",
    "just",
    "experience",
    "experienced",
    "strong",
    "ability",
    "able",
    "work",
    "working",
    "works",
    "years",
    "year",
    "plus",
    "preferred",
    "required",
    "including",
    "include",
    "includes",
    "etc",
    "e.g",
    "i.e",
}


def _norm_ws(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip().lower())


@lru_cache(maxsize=1)
def alias_index() -> dict[str, str]:
    """alias (lowercase) -> canonical term."""
    idx: dict[str, str] = {}
    for canon, aliases in ALIASES.items():
        idx[_norm_ws(canon)] = canon
        for a in aliases:
            idx[_norm_ws(a)] = canon
    return idx


def canonical(term: str) -> str:
    """Map a term (any spelling) to its canonical lexicon form, or its normalized self."""
    t = _norm_ws(term)
    return alias_index().get(t, t)


def known_term(text: str) -> bool:
    """True when the whole text is a lexicon term or alias (not merely contains one)."""
    return _norm_ws(text) in alias_index()


@lru_cache(maxsize=1)
def term_pattern() -> re.Pattern[str]:
    """Compiled alternation of every alias, longest first (public for the validator's binding coverage)."""
    terms = sorted(alias_index().keys(), key=len, reverse=True)
    parts = []
    for t in terms:
        esc = re.escape(t)
        # word boundaries that also cope with terms like "c#", "node.js", "ci/cd"
        parts.append(rf"(?<![A-Za-z0-9#+]){esc}(?![A-Za-z0-9#+])")
    return re.compile("|".join(parts), re.IGNORECASE)


def find_terms(text: str) -> list[str]:
    """Canonical lexicon terms found in ``text`` (deduplicated, in order of appearance)."""
    found: list[str] = []
    seen: set[str] = set()
    for m in term_pattern().finditer(text):
        c = alias_index().get(_norm_ws(m.group(0)))
        if c and c not in seen:
            seen.add(c)
            found.append(c)
    return found


# Concept groups whose members are practices / capabilities rather than platforms: a JD naming one
# of these asks for a capability (segmentation, data governance), not a tool.
CAPABILITY_GROUPS = {
    "process",
    "delivery",
    "reliability_ops",
    "implementation",
    "soft",
    "quality",
    "automation_general",
    "data_modeling",
    "error_handling_fam",
    "agent_quality",
    "governance",
    "finance_analysis",
    "close_ops",
    "spreadsheet_skills",
    "sales_eng",
}
DOMAIN_TERMS = {
    "finance",
    "financial operations",
    "revenue operations",
    "marketing operations",
    "sales operations",
    "customer success",
    "tax",
    "bookkeeping",
    "payroll",
    "compliance",
    "recruiting",
    "compensation",
    "subscription billing",
    "revenue assurance",
    "hr_domain",
}
_EXTRA_CAPABILITIES = {
    "segmentation",
    "analytics",
    "data flows",
    "data discrepancies",
    "marketing automation",
    "platform governance",
    "customer success operations",
    "customer health scoring",
    "customer lifecycle management",
    "renewal operations",
    "net revenue retention",
    "gross revenue retention",
    "logo retention",
}
# product names that are ordinary words elsewhere: only a platform *listing* ("tools such as Make, Clay") names the product
LIST_CONTEXT_ALIASES = {"make": "make.com"}


# A general capability the JD names is evidenced by hands-on work with any product that delivers it:
# Power BI or Google Analytics work supports "analytics", Marketo work supports "marketing automation".
# The relation is one-way. Evidence of the capability, or of a sibling product, never makes a *named*
# product more than TRANSFERABLE (Google Analytics is not Adobe Analytics; Power BI is not CJA), and
# a platform category that is a technology in its own right (CDP, CRM) is not a capability here.
CAPABILITY_PRODUCTS: dict[str, frozenset[str]] = {
    "analytics": frozenset(
        t for t in [*CONCEPT_GROUPS["product_analytics"], *CONCEPT_GROUPS["bi"]] if t != "bi"
    ),
    "marketing automation": frozenset(CONCEPT_GROUPS["marketing_automation"]),
}


def capability_products(term: str) -> frozenset[str]:
    """Products whose hands-on use evidences the general capability ``term`` (empty for anything else)."""
    return CAPABILITY_PRODUCTS.get(canonical(term), frozenset())


def evidenced_terms(bank_terms: set[str]) -> set[str]:
    """The bank's own terms plus every general capability one of its evidenced products delivers.
    Nothing flows the other way: a named product is evidenced only by itself."""
    return set(bank_terms) | {
        cap for cap, products in CAPABILITY_PRODUCTS.items() if products & bank_terms
    }


@lru_cache(maxsize=1)
def capability_terms() -> frozenset[str]:
    out = set(_EXTRA_CAPABILITIES)
    for g in CAPABILITY_GROUPS:
        out.update(CONCEPT_GROUPS.get(g, []))
    return frozenset(out)


def term_kind(term: str) -> str:
    """'domain' | 'capability' | 'technology' for a canonical lexicon term."""
    c = canonical(term)
    if c in DOMAIN_TERMS:
        return "domain"
    if c in capability_terms():
        return "capability"
    return "technology"


def group_of(term: str) -> list[str]:
    c = canonical(term)
    return [g for g, members in CONCEPT_GROUPS.items() if c in members]


def has_admin_cue(text: str) -> bool:
    t = text.lower()
    return any(cue in t for cue in ADMIN_CUES)


# Tokens that are lexicon "umbrella" words: matching them alone is weak evidence
GENERIC_TERMS = {
    "crm",
    "erp",
    "hris",
    "ats",
    "bi",
    "api",
    "finance",
    "compliance",
    "requirements gathering",
    "cms",
    "communication",
    "training",
    "change management",
    "bachelor's degree",
    "certification",
    "log analysis",
}
