"""Persistence layer.

All SQL lives here, hand-written rather than generated by an ORM. That is a
deliberate choice: the SQL we write is also the SQL that will be pasted into
Supabase when the Personal Alpha graduates to PostgreSQL, so the portability
decisions in Appendix A stay visible instead of being hidden by a framework.
"""
