"""Reading the Experience section of a LinkedIn PDF export.

WHY A SEPARATE READER
---------------------
`cv/propose.py` reads a CV, and a CV writes one role per line-group with the
employer, the place and the dates on one line:

    Northwind, Belo Horizonte, MG, Brazil (remote) Jun 2024 - Mar 2025

A LinkedIn PDF export does not. It writes a vendor TEMPLATE, and the template
puts the employer, the title and the dates on separate lines, groups several
roles under one employer, and inserts a total-duration line for the group:

    Contoso
    2 years 4 months
    Product Manager | Workflow Automation, API Integrations & Product
    Analytics
    February 2024 - July 2024 (6 months)

Pointing the CV reader at that produces what it produced before this file
existed: 255 employment claims with no employer on any of them, which cannot
take part in conflict detection at all -- so the one thing two documents are
for, disagreeing usefully, could not happen.

WHAT IT ANCHORS ON, AND WHY THAT ONE
-------------------------------------
**The date line.** `March 2025 - September 2026 (1 year 7 months)` is
machine-generated by the template: month name, year, separator, month name and
year or `Present`, and a parenthesised duration. It is the only line in the
section whose shape is the vendor's rather than the author's, which makes it
the only safe thing to anchor on. Everything else -- a title, a company name, a
bullet -- is text somebody typed and could be anything.

From each date line the reader walks BACKWARDS through the role's header,
stopping at the first line that belongs to the previous role's body. A line
belongs to a body when it ends a sentence, starts with a bullet, or is a page
footer. What is left is the header; its first line is the employer when the
header has one, and when it does not the employer is the one most recently
established -- which is how LinkedIn's grouped roles are meant to read.

**A group-duration line ends the walk and names the employer above it.**
`2 years 4 months` on its own line is the template's group header, so the line
above it is the company for every role that follows.

WHAT IT REFUSES TO DO
---------------------
**An employer it cannot establish stays None.** No fallback to the filename, no
guess from the title, no nearest-short-line. A claim with no employer simply
takes no part in conflict grouping, which is the correct consequence: grouping
on a guessed employer anchors a disagreement to the wrong role, and a wrong
conflict is worse than a missed one because it asks the candidate to resolve
something that was never in dispute.

**Read from the owner's own export, 2026-09-07.** The template is a fact about
LinkedIn's PDF renderer, recorded on a date, exactly as a provider's response
shape is. The fixture beside the tests is written to that shape and invented;
no line of anybody's real profile is committed.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

#: The vendor's own date line. `Present` is LinkedIn's word for a current role.
#: The parenthesised duration is optional because the template omits it for
#: some very short spans.
DATE_LINE = re.compile(
    r"^(?P<start>[A-Za-zçÇ]{3,12}\.?\s+\d{4})"
    r"\s*[-]\s*"  # punctuation-check: allow
    r"(?P<end>[A-Za-zçÇ]{3,12}\.?\s+\d{4}|Present|Presente|Atual)"
    r"\s*(?:\(.*\))?$",
    re.IGNORECASE,
)

#: The template's group header: how long somebody was at one employer in total,
#: across several roles. The line ABOVE it is the employer.
GROUP_DURATION = re.compile(
    r"^\d+\s+(?:years?|anos?|year|ano)(?:\s+\d+\s+(?:months?|mes(?:es)?))?$"
    r"|^\d+\s+(?:months?|mes(?:es)?)$",
    re.IGNORECASE,
)

#: The page footer the renderer inserts. Never content.
PAGE_MARKER = re.compile(r"^\s*Page \d+ of \d+\s*$", re.IGNORECASE)

#: How a bullet arrives once the PDF text layer has been read. The character
#: varies by extractor, so the test is "starts with something that is not a
#: letter, a digit or an opening quote".
BULLET = re.compile(r"^[^\w\"'(\[]")

#: The section headings the template uses, in the languages it renders.
_EXPERIENCE = {"experience", "experiencia", "experiência"}
_ENDS_EXPERIENCE = {
    "education",
    "educacao",
    "educação",
    "formacao academica",
    "licenses & certifications",
    "certifications",
    "skills",
    "languages",
    "idiomas",
    "honors-awards",
    "publications",
}

#: How long a line may be and still plausibly be a company name. A company name
#: is a noun phrase; a body sentence that happens not to end in a full stop is
#: usually much longer.
MAX_EMPLOYER_LENGTH = 80


@dataclass(frozen=True)
class Position:
    """One role, as the template stated it."""

    employer: str | None
    title: str
    #: The date line, verbatim. Parsed by `intake.build.read_period`, which is
    #: the one place a period is read, so a LinkedIn date and a CV date go
    #: through identical code.
    period_line: str
    body: tuple[str, ...] = field(default_factory=tuple)


def _normalise(text: str) -> list[str]:
    """The document as lines, with the renderer's artefacts removed.

    Non-breaking spaces become spaces: the template writes them around the
    date separator, and a regex looking for a plain hyphen surrounded by
    spaces does not match `March 2025\\xa0-\\xa0September 2026`.
    """
    return [line.replace("\xa0", " ").rstrip() for line in text.splitlines()]


def experience_span(lines: list[str]) -> tuple[int, int] | None:
    """Where the Experience section starts and stops, or None.

    Bounded by the next section heading rather than by the end of the file, so
    that education dates and certification dates cannot be read as roles.
    """
    start = None
    for index, line in enumerate(lines):
        if line.strip().casefold() in _EXPERIENCE:
            start = index + 1
            break
    if start is None:
        return None

    for index in range(start, len(lines)):
        if lines[index].strip().casefold() in _ENDS_EXPERIENCE:
            return (start, index)
    return (start, len(lines))


def _is_body(line: str) -> bool:
    """Whether a line belongs to a role's prose rather than to its header.

    Three signals, all structural: it finishes a sentence, it starts as a
    bullet, or it is the renderer's page footer. A header line -- a company
    name, a title, a wrapped title -- does none of those.
    """
    stripped = line.strip()
    if not stripped:
        return True
    if PAGE_MARKER.match(stripped):
        return True
    if BULLET.match(stripped):
        return True
    return stripped.endswith((".", ":", ";"))


def _header_before(lines: list[str], index: int, floor: int) -> list[str]:
    """The header lines above a date line, nearest last.

    Stops at the first body line, at the section boundary, or after four lines
    -- a company plus a title wrapped over three lines is already generous, and
    an unbounded walk would swallow a whole paragraph the moment one body line
    happened to lack its full stop.
    """
    header: list[str] = []
    cursor = index - 1
    while cursor >= floor and len(header) < 4:
        line = lines[cursor]
        if _is_body(line):
            break
        header.append(line.strip())
        if GROUP_DURATION.match(line.strip()):
            # The template's group header. The employer is the line above it,
            # and the walk stops there because everything further up belongs
            # to the previous role.
            if cursor - 1 >= floor and not _is_body(lines[cursor - 1]):
                header.append(lines[cursor - 1].strip())
            break
        cursor -= 1
    header.reverse()
    return [h for h in header if h]


#: Characters a company line in this template does not contain.
#:
#: The template writes a company as a BARE NOUN PHRASE on its own line. A
#: header line carrying any of these is a compound title the author wrote
#: ("Senior Solutions Engineer | Enterprise Integration Architecture, iPaaS"),
#: or one of their keyword lines ("Keywords: Project Management, ..."), or a
#: fragment of body prose that happened not to end in a full stop.
#:
#: Measured against the owner's own export 2026-09-07: without this rule the
#: reader took a wrapped title line as the employer on 7 of 12 positions, which
#: is the failure mode that matters. A wrong employer anchors a disagreement to
#: the wrong role and asks the candidate to resolve something that was never in
#: dispute; a missing one merely takes that role out of conflict detection.
_NOT_IN_A_COMPANY_NAME = ("|", ":", ",")


def looks_like_a_company(line: str) -> bool:
    """Whether this header line can be read as an employer at all.

    Positive identification, never elimination. Everything this cannot
    positively recognise is left for the group to supply or left as None.
    """
    stripped = line.strip()
    if not stripped or len(stripped) > MAX_EMPLOYER_LENGTH:
        return False
    if any(ch in stripped for ch in _NOT_IN_A_COMPANY_NAME):
        return False
    # A line starting lower case is the middle of a sentence. The template
    # never starts a company name that way.
    return stripped[0].isupper() or stripped[0].isdigit()


def _split_header(header: list[str]) -> tuple[str | None, str, bool]:
    """A header into `(employer, title)`.

    Two shapes, and nothing is guessed outside them:

    1. The header contains the template's GROUP_DURATION line. The company is
       the line above it, and everything after it is the title.
    2. The header has two or more lines and the topmost passes
       `looks_like_a_company`. That one is the company.

    Anything else yields no employer. A lone header line is a title; a topmost
    line carrying a pipe, a colon or a comma is a title the author wrapped.

    The third value says whether this header STARTS A NEW EMPLOYER GROUP, and
    it is what stops the reader carrying a name forward past the end of the
    group it belongs to. A GROUP_DURATION line proves a new employer begins
    even when the name above it cannot be read -- so the answer there is None
    and a boundary, never the previous company. Without that, the owner's own
    export inherited one employer across four roles at three other companies.
    """
    duration = next((i for i, h in enumerate(header) if GROUP_DURATION.match(h)), None)
    if duration is not None:
        employer = header[duration - 1].strip() if duration >= 1 else None
        title = " ".join(header[duration + 1 :]).strip()
        if employer and looks_like_a_company(employer):
            return (employer, title, True)
        return (None, title, True)

    if len(header) >= 2 and looks_like_a_company(header[0]):
        return (header[0].strip(), " ".join(header[1:]).strip(), True)
    return (None, " ".join(header).strip(), False)


def read_positions(text: str) -> list[Position]:
    """Every role the Experience section states, in the order it states them.

    An employer established by one block carries forward to the blocks under
    it, which is what LinkedIn's grouping means. It never carries BACKWARDS: a
    role above the first company line has no employer, and gets None.
    """
    lines = _normalise(text)
    span = experience_span(lines)
    if span is None:
        return []
    start, end = span

    date_indices = [i for i in range(start, end) if DATE_LINE.match(lines[i].strip())]
    headers = {index: _header_before(lines, index, start) for index in date_indices}
    positions: list[Position] = []
    established: str | None = None

    for order, index in enumerate(date_indices):
        header = headers[index]
        employer, title, boundary = _split_header(header)
        if boundary:
            # A new employer begins here whether or not its name could be
            # read. Resetting on an unreadable one is the whole point: a name
            # carried past its group is a WRONG employer, and a wrong employer
            # anchors a disagreement to a role that was never in dispute.
            established = employer
        # The body stops where the NEXT role's header begins, not at its date
        # line. Without the subtraction, one role's body swallowed the next
        # role's company and title -- so on the owner's own export one employer's
        # title was filed as a claim about the previous employer, and landed
        # in that employer's disagreement group.
        if order + 1 < len(date_indices):
            following = date_indices[order + 1]
            body_end = max(index + 1, following - len(headers[following]))
        else:
            body_end = end
        body = [
            lines[i].strip()
            for i in range(index + 1, body_end)
            if lines[i].strip() and not PAGE_MARKER.match(lines[i].strip())
        ]
        positions.append(
            Position(
                employer=employer or established,
                title=title,
                period_line=lines[index].strip(),
                body=tuple(body),
            )
        )
    return positions
