"""The source matrix as a document, rendered from the measurement.

WHY THE DOCUMENT IS GENERATED
-----------------------------
`docs/product/source-capability-matrix.md` is written by hand and it is the
right shape for what it holds: prose about WHY each source is where it is, with
quotes from first-party pages and the dates they were read. That kind of
argument cannot be generated and should not be.

A STATUS is the opposite. "Workable: blocked" was true on the day somebody
typed it and is a claim about today every time anybody reads it, and this
project has misled itself that way more than once -- a catalogue row said
PLANNED over 409 collected postings, and `source-health` printed "Never
collected" above a count of 409.

So this file renders the MEASUREMENT, with the database it was measured against
and the date, and `career-agent source-matrix --write` is how it is refreshed.
Anything in it that cannot be measured is not in it.

THE COLUMNS ARE THE QUESTION
----------------------------
Not "is this source good". Whose move it is, and what the move is. A reader
scanning the table should be able to stop at the first row whose next action is
theirs.
"""

from __future__ import annotations

from pathlib import Path

from career_agent.clock import now_utc
from career_agent.sources.matrix import MatrixRow, MatrixState, summarise

#: The order states are presented in: the ones somebody can act on first.
#:
#: NOT the enum's own order, which runs worst-to-best and puts ten rows nobody
#: can do anything about at the top of the page. A document is read from the
#: top, so the top is where the owner's own move goes.
READING_ORDER: tuple[MatrixState, ...] = (
    MatrixState.PRODUCTION,
    MatrixState.PRODUCTION_EMPTY,
    MatrixState.NOT_STARTED,
    MatrixState.FAILED,
    MatrixState.READY_OWNER_RUN,
    MatrixState.DISABLED_QUOTA,
    MatrixState.BLOCKED_PROVIDER,
    MatrixState.PERMITTED_NOT_BUILT,
    MatrixState.NOTHING_PUBLISHED,
    MatrixState.FORBIDDEN,
)

_HEADER = """<!--
GENERATED by `career-agent source-matrix --write`. Do not edit by hand.

Edit `config/source_catalogue.yaml` for what a vendor permits, or
`src/career_agent/sources/matrix.py` for how a state is derived, and run the
command again.

The prose about WHY each row is what it is lives in
`docs/product/source-capability-matrix.md`, which is hand-written on purpose and
is a different document.
-->

# The source matrix

What works, what does not, why, and what has never run.

Every number here is **measured** against one database at one moment, and both
are named below. Nothing in this file is a remembered claim: a status written in
prose on one day and read as current on another is the most reliable way this
project has misled itself.

"""

#: What each state means, and whose move it is.
#:
#: A TABLE OF DATA rather than a markdown literal, because a markdown row is one
#: long line and this file is linted at a hundred characters. Composing it keeps
#: the sentences readable in the source as well as in the output.
_MEANINGS: tuple[tuple[MatrixState, str, str], ...] = (
    (MatrixState.NOT_STARTED, "Implemented; never run in this database.", "Run verified boards."),
    (
        MatrixState.FAILED,
        "Attempted without production inventory.",
        "Resolve the recorded failure.",
    ),
    (
        MatrixState.PRODUCTION,
        "Postings from it are in the corpus.",
        "Nobody's. Keep collecting.",
    ),
    (
        MatrixState.PRODUCTION_EMPTY,
        "A successful verified run found no openings.",
        "Refresh on schedule.",
    ),
    (
        MatrixState.READY_OWNER_RUN,
        "Built and permitted, and the first live call is the **owner's**.",
        "The owner's, and only the owner's.",
    ),
    (
        MatrixState.DISABLED_QUOTA,
        "A budget we or the vendor set is spent.",
        "Wait, or ask the vendor.",
    ),
    (
        MatrixState.BLOCKED_PROVIDER,
        "The vendor's own endpoint is refusing us today.",
        "Diagnose the endpoint.",
    ),
    (
        MatrixState.PERMITTED_NOT_BUILT,
        "Nothing stops us and there is no adapter.",
        "Write one.",
    ),
    (
        MatrixState.NOTHING_PUBLISHED,
        "No ordinary public job-board inventory is published.",
        "Nobody's.",
    ),
    (
        MatrixState.FORBIDDEN,
        "A first-party page forbids automated access.",
        "**Nobody's. Do not fetch.**",
    ),
)

_LEGEND_NOTE = (
    "`READY_OWNER_RUN` is the row that matters most and the one a table cell "
    "cannot hold: either a robots file names the agent specifically, or a "
    "credential's whole budget belongs to one person. `OWNER_RUN_ONLY` in "
    "`src/career_agent/sources/matrix.py` names each source and quotes the "
    "reason, and moving a source out of it costs a reviewable commit -- which is "
    "what an ethical boundary should cost.\n"
)


def _legend() -> list[str]:
    lines = [
        "## The states\n",
        'Each one answers "whose move is it", which is the question the other five',
        "source vocabularies in this repository cannot answer between them.\n",
        "| State | What it means | Whose move |",
        "|---|---|---|",
    ]
    lines.extend(f"| `{state.value}` | {meaning} | {move} |" for state, meaning, move in _MEANINGS)
    lines.append("")
    lines.append(_LEGEND_NOTE)
    return lines


def _row(row: MatrixRow) -> str:
    """One table row. Every cell is a measurement or a quoted permission."""
    held = "--" if row.postings is None else f"{row.postings:,}"
    scored = "--" if row.scored is None else f"{row.scored:,}"
    full = "--" if row.full_content is None else f"{row.full_content:,}"
    last = row.last_success or "never"
    percent = (
        f"{100 * row.full_content / row.postings:.1f}%"
        if row.postings and row.full_content is not None
        else "--"
    )
    if percent == "100.0%" and row.full_content != row.postings:
        percent = "<100%"
    limitation = row.coverage_limitation.replace("|", "\\|").replace("\n", " ")
    blocker = (row.blocker or "--").replace("|", "\\|").replace("\n", " ")
    return (
        f"| {row.name} | `{row.source_id}` | {row.region} | {row.permission} "
        f"| {row.maturity} | {'yes' if row.production_enabled else 'no'} "
        f"| {'yes' if row.ever_run else 'no'} | {last} | {held} | {scored} | {full} "
        f"| {percent} | {row.refresh_state} | {inventory_shape(row)} | {limitation} | {blocker} "
        f"| {row.next_action} |"
    )


def inventory_shape(row: MatrixRow) -> str:
    """What the postings from this source ARE, in one word the reader can act on.

    Separate from `refresh_state`, which says how the last run ended:

    * `METADATA_ONLY`: every posting lacks the advert; scores are near zero
      and the rows are leads. Shown before `QUERY_SCOPED` when both apply,
      because a reader deciding whether to open the list needs to know there
      is no advert to read.
    * `QUERY_SCOPED`: the source answers bounded questions and no run can
      reach its whole market (Jobgether, 250 rows a question).
    * `PRODUCTION_COMPLETE`: the last run reached the end of what the source
      serves.
    * `PRODUCTION_PARTIAL`: it did not, by our budget or the vendor's cap.
    * `--` for a source with nothing persisted.
    """
    if not row.postings:
        return "--"
    if row.full_content == 0 and row.scored:
        return "METADATA_ONLY"
    if row.query_scoped:
        return "QUERY_SCOPED"
    if row.refresh_state.startswith("COMPLETE"):
        return "PRODUCTION_COMPLETE"
    return "PRODUCTION_PARTIAL"


_COLUMNS = (
    "| Source | Id | Region | Permission | Maturity | In the production path | "
    "Ever run here | Last successful run | Open postings | Scored | Whole advert "
    "| Full-content % | Refresh state | Inventory | Coverage limitation | Blocker | Next action |\n"
    "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"
)


def render(rows: list[MatrixRow], *, database: Path | None = None) -> str:
    """The whole document.

    `database` is printed rather than inferred, because every count below is a
    fact about one file and the most common way to be confused by this product
    is to read a number from the wrong database.
    """
    counts = summarise(rows)
    parts: list[str] = [_HEADER]

    parts.append(f"**Measured** {now_utc()}\n")
    # POSIX separators, so the committed document does not change every time it
    # is regenerated on a different operating system. The path is a fact about
    # which file was measured, and `data\\m1d2` and `data/m1d2` are the same
    # fact spelled two ways.
    shown = database.as_posix() if database else None
    parts.append(f"**Database** `{shown}`\n" if shown else "**Database** none\n")
    parts.append(f"**Sources in the catalogue** {len(rows)}\n")
    parts.append("")

    parts.append("## How many in each state\n")
    parts.append("| State | Sources |")
    parts.append("|---|---|")
    for state in READING_ORDER:
        parts.append(f"| `{state.value}` | {counts[state.value]} |")
    parts.append("")
    parts.append(
        'A zero is kept rather than omitted. "No source is being refused by its '
        'own endpoint today" is worth reading, and a table that left the row out '
        "would leave somebody to infer it.\n"
    )

    for state in READING_ORDER:
        group = [row for row in rows if row.state is state]
        if not group:
            continue
        parts.append(f"## {state.value} -- {state.label}\n")
        parts.append(_COLUMNS)
        parts.extend(_row(row) for row in group)
        parts.append("")

    parts.extend(_legend())
    parts.append("## What the columns mean\n")
    parts.append(
        "**Permission** follows the first-party evidence recorded in "
        "`config/source_catalogue.yaml`. ADR-0018 permits public collection in "
        "the absence of an explicit prohibition, while preserving authentication, "
        "access-control, CAPTCHA and rate-limit boundaries. An affirmative vendor "
        "grant is recorded separately from policy silence.\n"
    )
    parts.append(
        "**Maturity** is how far the code got, asked of the provider registry and "
        "the corpus rather than of the catalogue. An adapter existing is not the "
        "source working.\n"
    )
    parts.append(
        "A registered implementation matching the source id is recognized even "
        "when the catalogue deliberately omits a production provider. Such a "
        "source can be BUILT and FORBIDDEN with production disabled; implementation "
        "does not imply permission or persisted inventory.\n"
    )
    parts.append(
        "**Last successful run** reads this provider's own run evidence. Shared "
        "board runs count only families with attempted and successful boards in "
        "their by_provider slice. Another family's run proves nothing here. "
        "An unfinished ledger row reads RUNNING_OR_INTERRUPTED; the ledger alone "
        "cannot establish that its process still exists.\n"
    )
    parts.append(
        "**Scored** counts open postings with a stored score for their current content hash, "
        "across configuration versions. It sits beside "
        "**Whole advert** because a source collected after the last rescore has "
        'postings, no scores, and therefore no measured content depth -- and "not '
        'measured yet" must never render as "none of these is complete".\n'
    )
    parts.append(
        "**Whole advert** counts current-content matches with "
        "`job_match.content_completeness = FULL_CONTENT`, "
        "`COUNT(DISTINCT job_id)`. The DISTINCT is a bug fix: `job_match` holds one "
        "row per (posting, configuration version) and a corpus carries several, so "
        "a plain count reported nearly three times as many complete postings for one "
        "source as that source has postings.\n"
    )
    return "\n".join(parts) + "\n"
