"""Derive the neutral starting configuration from the worked example.

`config/search.worked-example.yaml` is one person's real job search: forty-nine
signals about revenue operations and integration platforms, a Brazilian
candidate country, and a taxonomy of the titles that work is posted under. It
is an excellent EXAMPLE and it is a bad DEFAULT, because a stranger who clones
this repository and runs `setup` inherits somebody else's career.

So there are two files. The example stays exactly as it is, because it is the
owner's working configuration and the one every stored score in the corpus is
keyed to. `config/search.starter.yaml` is the same machine with the person
taken out of it.

    uv run python scripts/make_starter_config.py

DERIVED rather than hand-written, and that is the point. The configuration has
eighteen top-level sections, several of which are scoring machinery that must
keep working: prominence multipliers, negation windows, normalisation rules,
component maxima that a test requires to sum to one hundred. Writing a second
copy by hand would produce a file that drifts from the first one the next time
either changes. This empties the parts that are a PERSON and keeps the parts
that are a MECHANISM, and a test loads the result through the real loader.

WHAT IS EMPTIED, and why each one is a person rather than a mechanism:

  label                        what this search is called
  lexicon                      the phrases that score, which is the search
  scoring.*.weights            which of those phrases are worth what
  scoring.soft_penalties       the phrases somebody wants less of
  taxonomy.*                   the titles the work is posted under
  ambiguous_titles             titles that mean different things per person
  eligibility.candidate_*      where somebody lives
  eligibility.blockers         what rules them out
  eligibility.eligible_*       where they may work
  preferences                  what they prefer
  screening                    what they will not look at
  sources.enabled              which boards to read, which is a choice
  scoring.components.*.label   what each kind of evidence is CALLED

THE INVARIANT THIS FILE ENFORCES
--------------------------------
**Default product behaviour must not encode one user's career.** A lawyer, a
student, a nurse, a salesperson and an engineer must all get the same neutral
structure out of a fresh clone, and every occupational preference must come
from their own profile.

Two things broke that and survived the first pass, both because they are DATA
rather than values and so did not look like preferences:

  the component LABELS. `automation_integration` was called "Automation, API
  and integration signals" in the starter, and that label is rendered on the
  score breakdown of every posting. A nurse opening a fresh install was shown
  a scoring dimension named after somebody else's job. The KEYS stay -- they
  are structural, named in `match/score.py` and in `search_config.py`, and
  renaming them is a schema migration plus a rescore of every stored row --
  but what a person READS is a label, and a label is data.

  `sources.enabled`, which listed Greenhouse, Lever and Ashby: three
  technology applicant-tracking systems, copied from the example. It is also
  INERT -- nothing in this codebase reads `config.sources.enabled`, and
  `config/source_catalogue.yaml` is the authority on which providers can be
  read -- so the only thing it was doing was telling a stranger that Career
  Agent reads technology boards. Emptied, and the header says where the real
  answer lives.
"""

from __future__ import annotations

import copy
from pathlib import Path
from typing import Any

import yaml

CONFIG = Path(__file__).resolve().parents[1] / "config"
EXAMPLE = CONFIG / "search.worked-example.yaml"
STARTER = CONFIG / "search.starter.yaml"

HEADER = """# =====================================================================
# The neutral starting point.
#
# GENERATED by `scripts/make_starter_config.py` from `search.worked-example.yaml`.
# Do not edit this file by hand: edit the generator, or edit YOUR OWN
# `search.local.yaml`, which is what `career-agent setup` writes and what
# overrides everything here.
#
# It is the same machine as the example with the person taken out. Every
# scoring component, every prominence multiplier, every negation window and
# every threshold survives; the phrases, the titles, the country, the target
# regions and the preferences are empty, because those are yours.
#
# A search with an empty lexicon scores every posting at zero on the phrase
# components, which is correct rather than broken: nothing has been said yet
# about what you are looking for. `career-agent setup` is how you say it.
#
# NOTHING HERE NAMES AN OCCUPATION, and that is a rule rather than a tidy-up.
# A lawyer, a student, a nurse, a salesperson and an engineer get this same
# file. Every occupational preference belongs in your own answers.
#
# `sources.enabled` is empty and inert. Which job boards Career Agent can
# actually read is recorded in `config/source_catalogue.yaml`, measured per
# provider, and it is not a preference.
# =====================================================================

"""

#: Sections replaced wholesale with an empty container of the same shape.
EMPTIED: dict[str, Any] = {
    "lexicon": {},
    "ambiguous_titles": {},
}

#: `taxonomy` keeps its keys and loses its contents. The keys are the shape
#: the matcher expects; the values are one person's job titles.
TAXONOMY_KEYS = ("primary", "conditional", "strong_adjacent", "excluded", "fragments")

#: What each scoring component is CALLED in a neutral installation.
#:
#: The keys are structural and stay: `match/score.py` names all three, and
#: `search_config.py` requires them. The labels are what a person reads on a
#: score breakdown, and the example's labels describe one person's trade --
#: "Automation, API and integration signals" is a sentence about systems work
#: and about nothing else.
#:
#: Each replacement says what the component actually measures in a file whose
#: weights are empty: a group of phrases the person named. Naming them
#: "first", "second" and "third" would be honest and useless; naming them
#: after a profession is neither.
NEUTRAL_COMPONENT_LABELS: dict[str, str] = {
    "responsibilities": "The work itself, in your words",
    "technologies": "Tools and systems you named",
    "automation_integration": "Other phrases you said matter",
}


def _blank_like(value: Any) -> Any:
    """An empty container of the same TYPE, so the schema still validates."""
    if isinstance(value, dict):
        return {}
    if isinstance(value, list):
        return []
    if isinstance(value, str):
        return ""
    return value


def derive(example: dict[str, Any]) -> dict[str, Any]:
    config = copy.deepcopy(example)

    config["label"] = "My job search"
    config["config_id"] = "my-search"
    config["config_version"] = 1

    for key, empty in EMPTIED.items():
        if key in config:
            config[key] = copy.deepcopy(empty)

    taxonomy = config.get("taxonomy")
    if isinstance(taxonomy, dict):
        for key in TAXONOMY_KEYS:
            if key in taxonomy:
                taxonomy[key] = _blank_like(taxonomy[key])

    scoring = config.get("scoring")
    if isinstance(scoring, dict):
        components = scoring.get("components")
        if isinstance(components, dict):
            for name, component in components.items():
                # THE LABEL IS DATA AND THE KEY IS STRUCTURE. See
                # `NEUTRAL_COMPONENT_LABELS`: a component a fresh install can
                # never score must not be named after somebody's profession,
                # because the breakdown prints the label on every posting.
                if isinstance(component, dict) and name in NEUTRAL_COMPONENT_LABELS:
                    component["label"] = NEUTRAL_COMPONENT_LABELS[name]
                # The MAXIMA stay. A test requires them to sum to one hundred,
                # and they describe how much each kind of evidence is worth
                # relative to the others, which is a design decision this
                # project made rather than a preference somebody expressed.
                if isinstance(component, dict) and "weights" in component:
                    component["weights"] = {}
                if isinstance(component, dict) and "class_points" in component:
                    # `role_family` scores a title CLASS, and with an empty
                    # taxonomy nothing is ever classified as anything but the
                    # fallback. The points stay so the component still has a
                    # shape; they simply never fire.
                    pass
        penalties = scoring.get("soft_penalties")
        if isinstance(penalties, dict) and "weights" in penalties:
            penalties["weights"] = {}

    eligibility = config.get("eligibility")
    if isinstance(eligibility, dict):
        # A country with no answer is not a country. `setup` asks for it, and
        # the loader requires the key to exist.
        eligibility["candidate_country"] = ""
        eligibility["candidate_country_label"] = ""
        for key in ("blockers", "eligible_countries", "eligible_scopes"):
            if key in eligibility:
                eligibility[key] = _blank_like(eligibility[key])
        if "positive_scope_patterns" in eligibility:
            eligibility["positive_scope_patterns"] = {}

    # `preferences` keeps its SECTIONS and loses its VALUES, and the two
    # halves of that were learned separately.
    #
    # The sections are required: `remote`, `contract`, `seniority`, `travel`,
    # `compensation` and `recency` are structured, not a free mapping of
    # somebody's opinions, and the loader refuses a configuration missing any
    # of them. That is why this file is generated rather than hand-written.
    #
    # The values are a person. The starter shipped with `[MID, SENIOR, LEAD]`
    # seniority, `[REMOTE, HYBRID]` work models, `[FULL_TIME_EMPLOYEE,
    # CONTRACTOR_B2B, EOR]` contracts and `[WORLDWIDE, LATAM, AMERICAS]` target
    # regions -- one person's answers, in the file whose whole purpose is to
    # have none. A stranger in Poland began their search aimed at Latin
    # America. `setup` asks for every one of these.
    #
    # `travel.max_tolerated_pct` and `recency` survive with their numbers,
    # because both are inert here rather than opinions: travel tolerance is
    # read only by the `travel_incompatible` blocker, which the starter does
    # not have, and recency is a display window rather than a filter.
    preferences = config.get("preferences")
    if isinstance(preferences, dict):
        for section, keys in (
            ("remote", ("accepted_work_models",)),
            ("contract", ("preferred", "unwanted")),
            ("seniority", ("preferred",)),
        ):
            block = preferences.get(section)
            if isinstance(block, dict):
                for key in keys:
                    if key in block:
                        block[key] = _blank_like(block[key])
        remote = preferences.get("remote")
        if isinstance(remote, dict) and "require_remote" in remote:
            remote["require_remote"] = False

    regions = config.get("regions")
    if isinstance(regions, dict):
        for key in ("target", "opportunistic"):
            if key in regions:
                regions[key] = _blank_like(regions[key])

    # `screening` keeps its SHAPE and loses its contents, for a different
    # reason the loader also taught: `required_any_groups[].any_of` names
    # lexicon signals, and the loader refuses a group keyed by a signal that
    # does not exist, because such a group can never fire. An empty lexicon
    # therefore requires empty groups. That referential check is the reason
    # this file is derived at all: hand-writing it would have shipped a
    # starter that does not load.
    screening = config.get("screening")
    if isinstance(screening, dict):
        screening["required_any_groups"] = []
        screening["required_all"] = []

    # `sources.enabled` named three technology applicant-tracking systems,
    # copied from the example. `priority` stays: it orders ACCESS METHODS --
    # a structured feed beats scraped HTML -- which is a fact about data
    # quality rather than about anybody's trade.
    #
    # Nothing in this codebase reads `config.sources.enabled`. That makes this
    # the cheapest possible fix and it is not the reason for it: a file whose
    # whole purpose is to have no person in it was telling a stranger which
    # industry this product is for.
    sources = config.get("sources")
    if isinstance(sources, dict) and "enabled" in sources:
        sources["enabled"] = {}

    return config


def main() -> int:
    example = yaml.safe_load(EXAMPLE.read_text(encoding="utf-8"))
    starter = derive(example)
    body = yaml.safe_dump(starter, sort_keys=False, allow_unicode=True, width=100)
    STARTER.write_text(HEADER + body, encoding="utf-8")

    kept = [key for key in example if key in starter]
    print(f"wrote {STARTER.relative_to(CONFIG.parent)}")
    print(f"  {len(kept)} of {len(example)} top-level sections kept")
    print(f"  lexicon: {len(example.get('lexicon', {}))} signals -> {len(starter['lexicon'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
