"""The published schema is exactly what the models produce.

`schemas/career-agent-import.v1.0.json` is a CONTRACT: it is what an assistant
or a person reads to produce a valid package without reading this repository.
A contract maintained by hand beside the models it describes drifts the first
time somebody adds a field to one of them, and the drift is silent -- packages
keep validating against the models while the published schema quietly describes
a different file.

So the schema is generated by `scripts/make_intake_schema.py` and this asserts
the committed copy is byte-identical to what that produces. Same discipline as
`config/search.starter.yaml` and its generator.
"""

from __future__ import annotations

import json
from pathlib import Path

from career_agent.intake.models import CURRENT_SCHEMA_VERSION, FORBIDDEN_KEYS

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "schemas" / f"career-agent-import.v{CURRENT_SCHEMA_VERSION}.json"


def test_the_committed_schema_is_what_the_generator_writes() -> None:
    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    from make_intake_schema import build  # noqa: PLC0415

    expected = json.dumps(build(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    actual = SCHEMA_PATH.read_text(encoding="utf-8")

    assert actual == expected, (
        "the published schema no longer matches the models. Run:\n"
        "  uv run python scripts/make_intake_schema.py"
    )


def test_the_schema_is_versioned_in_its_filename_and_its_body() -> None:
    """A schema whose version lives only in one place is one a reader can
    fetch by the wrong name and validate against anyway."""
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    assert CURRENT_SCHEMA_VERSION in SCHEMA_PATH.name
    assert CURRENT_SCHEMA_VERSION in schema["$id"]
    assert schema["properties"]["schema_version"]["enum"] == [CURRENT_SCHEMA_VERSION]


def test_the_schema_forbids_extra_properties_everywhere() -> None:
    """Otherwise a generator's invented field validates and arrives silently."""
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    assert schema.get("additionalProperties") is False
    for name, definition in schema["$defs"].items():
        if definition.get("type") == "object":
            assert definition.get("additionalProperties") is False, (
                f"$defs.{name} accepts unknown properties"
            )


def test_the_schema_says_what_it_refuses_and_why() -> None:
    """A validator reporting only "additional property" leaves the author
    guessing which of their extra fields was the problem."""
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    refused = schema["x-refused-keys"]
    assert set(refused["keys"]) == set(FORBIDDEN_KEYS)
    assert "verified" in refused["keys"]
    assert refused["why"].strip()


def test_a_metric_has_nowhere_to_put_a_bare_number() -> None:
    """The published half of "a figure is flagged and never lifted out"."""
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    metric = schema["$defs"]["MetricMention"]
    assert set(metric["properties"]) == {"original"}
